### ISSUE TITLE
Redundant line

### ISSUE THREAD

**Issue by haimav** [xdata-skylark/libskylark#10]
Looks like svd.hpp line 112 is redundant - has no effect.

**Comment by iff** [comment]
development branch?

**Comment by haimav** [comment]
It is on the dev branch as well. I put an issue because I didn't want to push the change without checking it, and was too busy to check it today.

**Comment by iff** [comment]
So, you are talking about https://github.com/xdata-skylark/libskylark/blob/development/nla/svd.hpp#L112 ?

**Comment by haimav** [comment]
Yes.

**Comment by haimav** [comment]
Looking at this again, I don't see why the line is redundant, so I am closing the issue.
