### ISSUE TITLE
linear_t, expsemigroup_t and matern_t should inherit from kernel_t but do not

### ISSUE THREAD

**Issue by haimav** [xdata-skylark/libskylark#13]
Missing implementations...

**Comment by jomsdev** [comment]
I am fixing that issue. I just write the code for the Linear kernel and seems to work (both, the C++ and the Python binding).

However, there is some part of the code that I would like to discuss. Now all the flow is working but:

- In the file [ckernel](https://github.com/xdata-skylark/libskylark/blob/capi/capi/ckernel.cpp#L11) the str2kernel_type function is using a macro defined in another file. Should we do that in that way?

- In the file [kernels.hpp](https://github.com/xdata-skylark/libskylark/blob/capi/ml/kernels.hpp#L78) the Gram() function defined inside a macro that will be expanded some lines below with multiple returns inside  the macro (which will finish the Gram() function) etc.. The flow of that functions is like a maze (macros expand before start to compile but the syntaxes make it easy confuse it with a function, etc). 

I am not sure how to do it in another way, but maybe you implement it like a "prototype", and now I could change it to make the code more readable/ mantenible.

Any comment about it?

**Comment by haimav** [comment]
@jomsdev 

Re macro in ckernel: it is defined in matrix_types.hpp which might not be the best place. Maybe we should define another hpp for macros.

Re kernels.hpp: Yes, this is a nightmarish maze, but I didn't find any other way to do it. If you have a good idea please share.

**Comment by jomsdev** [comment]
#28 solves that fact. All the kernels now inherit from kernel_t and implements the interface.
There is an exception: matern_t. I will open other issue related to that fact.

@haimav 
I will think about how ckernel and kernels.hpp could have a better flow. For now, I will let it "as is" given that is working and I understand the flow.
