### ISSUE TITLE
Polynomial Kernel

### ISSUE THREAD

**Issue by jomsdev** [xdata-skylark/libskylark#22]
I am working on the Python bindings for the kernel functions. The Gaussian kernel is now available, and I am trying to bind now the Polynomial kernel. I can call successfully the C++ code, but the result matrix seems to be wrong. If I am not wrong, the result matrix should be symmetric and contain ones along the diagonal. I have that little script (working):

```python 
import skylark.io as sl_io
import skylark.ml.kernels as sl_kernels
import El
# Read Data
X = El.DistMatrix()
L = El.DistMatrix()
K = El.DistMatrix()
sl_io.readlibsvm('data/usps.t', X, L, 0)

# Polynomial Kernel
Polynomial_kernel = sl_kernels.Polynomial(X.Height(), 1, 1, 1)
Polynomial_kernel.gram(X, K, 0, 0)
print K.Matrix().ToNumPy()[:1]

# Result of the print
# [[ 146.36290811   67.34598925   89.89811785 ...,  102.30962078
#    36.48056439  107.30371348]]
```

I am using the [usps.t](https://github.com/xdata-skylark/libskylark/tree/master/python-skylark/skylark/datasets) file, which is available with the Skylark installation.

I want to compare it with the result obtained from a C++ program. When I try to use Skylark in c++ directly but the result matrix is different. I checked the [kernel_regression.cpp](https://github.com/xdata-skylark/libskylark/blob/master/examples/kernel_regression.cpp) file as an entry point to learn how to use the kernels, but I am not sure if I am doing something wrong o  using bad the API. This is the C++ program:

```cpp
#include <iostream>
#include <El.hpp>
#include <skylark.hpp>
#include <boost/mpi.hpp>


int main(int argc, char* argv[]) {

    // Config parameters
    int seed = 38734;
    std::string fname = "/home/jms/notebooks/data/usps.t";

    // Initialize
    El::Initialize(argc, argv);

    boost::mpi::communicator world;
    int rank = world.rank();

    skylark::base::context_t context(seed);

    El::DistMatrix<double> X0, X, Y0, Y, K;

    // Read the file
    skylark::utility::io::ReadLIBSVM(fname, X0, Y0, skylark::base::COLUMNS,
            skylark::base::COLUMNS, -1);

    // Does not sample the data
    El::View(X, X0);
    El::View(Y, Y0);

    // Calculate the kernel
    std::shared_ptr<skylark::ml::kernel_t> k_ptr;
    k_ptr.reset(new skylark::ml::polynomial_t(X.Height(), 1, 1, 1));
    skylark::ml::kernel_container_t k(k_ptr);
    skylark::ml::Gram(skylark::base::COLUMNS, skylark::base::COLUMNS, k, X, Y, K);

    for (int i = 0; i < 2; ++i) {
        for (int j = 0; j < 5; ++j) {
            cout << K.Get(i,j) << " ";
        }
        cout << endl;
    }

    // output
    // -8.99999 -5.99999 -3 -5.99999 -5.99999 
    // -9 -6 -3 -6 -6 


    El::Finalize();
    return 0;
}
```

Any idea about why is not working?

**Comment by jomsdev** [comment]
I solved the problem and found a possible bug. 

I was using bad the C++ function:

```cpp
 skylark::ml::Gram(skylark::base::COLUMNS, skylark::base::COLUMNS, k, X, X, K);
```

The 5th parameter should be the same than te 4th (I am trying to compare de distances between a function and itself)

Anyway, I was doing it well from python but the result remains incorrect.


```python
Polynomial_kernel = sl_kernels.Polynomial(X.Height(), 1, 1, 1)
Polynomial_kernel.gram(X, K, 0, 0)
print K.Matrix().ToNumPy()[:1]

# Result of the print
# [[ 146.36290811   67.34598925   89.89811785 ...,  102.30962078
#    36.48056439  107.30371348]]
```

Should I go deeper with the C++ code or it is better if I focus bringing more functionalities to the python interface?

**Comment by haimav** [comment]
In general there is no restriction that the 5th parameter will be same as the 4th, only that both will have the same number of features. If you use "COLUMNS" in the Gram function, then this means that Height() should be the same for both. Obviously, when you used Y it was not having this property.

Now, if X and Y are different, but have same height, this is a valid call but you can (and will) end up with a non-symmetric matrix. If you use X in both parameters then you should get a symmetric matrix.

I will look into why you don't get that.

**Comment by jomsdev** [comment]
I did not check if the matrix was symmetric. But the problem seems to be that we don't get ones in the diagonal even when X and Y are the same matrix.

I guess that the 4th and 5th parameter can be different but then even having a symmetric matrix the diagonal will not have ones in the diagonal, right?

**Comment by haimav** [comment]
Hi, actually for the polynomial you will generally not get ones of the diagonal. (You do get ones on the diagonal for the Gaussian and Laplace kernel).

Basically the polynomail kernel is k(x,z) = (gamma^-1 * x^T z + c)^q. If gamma=1 and c=0 and every data vector has unit norm, then you will get 1s on the diagonal, but that is not the usual case.

**Comment by jomsdev** [comment]
Excellent, I did not know that property. I thought all the kernels should contain ones on the diagonal.

I am thinking about how to test it then. I guess that I could select some random i,j and calculate 
k(x,z) = (gamma^-1 * x^T z + c)^q 
then, compare the result with the matrix that the c++ returned me.

On the other hand, that only would be useful for the gram function. Any idea about how to test the rft function?

**Comment by jomsdev** [comment]
I will test it computing
```python
k(x,z) = (gamma^-1 * x^T z + c)^q 
```
To some/all the values in python and compare them to the C++ implementation given an example matrix. It is implemented and working so I close the issue.
