### ISSUE TITLE
Migarte to Travis CI

### ISSUE THREAD

**Issue by iff** [xdata-skylark/libskylark#25]
Migrate from our internal ci to travis-ci. Currently we are stuck with this until we have an Elemental deb package (building Elemental requires roughly 1300s). How about [caching](https://docs.travis-ci.com/user/caching/) build artefacts?

**Comment by poulson** [comment]
@andreasnoack recently added `ccache` support into [Elemental's Travis config](https://github.com/elemental/Elemental/blob/master/.travis.yml). Perhaps the same approach could be grafted into Skylark's Travis config. And, FWIW, I have some time to help with the Debian package again.

**Comment by iff** [comment]
Thanks for the pointer.. I'll give it a shot.

**Comment by iff** [comment]
The build is still slow and not using a matrix to test various compilers and MPI implementations (see #29).
