### ISSUE TITLE
Updating to the most recent version of Elemental

### ISSUE THREAD

**Issue by poulson** [xdata-skylark/libskylark#4]
For what it's worth, I have forked libskylark and updated its usage of Elemental to the current development branch:
https://github.com/poulson/libskylark/commit/8907dd524d1f3a44950620a4da5f2cf1ccc28804

There is close to a full C interface currently available, but not yet a Python interface built on top of it. Elemental 0.85 will be released soon, but I expect the Python interface to reappear in version 0.86.

**Comment by iff** [comment]
We provide support for Elemental 0.86 (rc1 at the moment) since 235b685 in the development branch. Once Elemental 0.86 is released we will merge it back to master.

**Comment by iff** [comment]
Closing this issue: we try to stay in sync with Elemental as best as we can on the development branch.

**Comment by poulson** [comment]
I apologize for not having a stable API yet. Sparse integration (and generalizing the data distributions) has continually led to the need for changes.
