### ISSUE TITLE
KernelRidge functions only admits DistMatrices<T>

### ISSUE THREAD

**Issue by jomsdev** [xdata-skylark/libskylark#44]
The function [KernelRidge](https://github.com/xdata-skylark/libskylark/blob/development/ml/krr.hpp#L94) only admits El::DistMatrix<T> as a parameters.
However, from the capi we are casting "DistMatrix" to El::ElementalMatrix<double> with the [skylark_void2any_root](https://github.com/xdata-skylark/libskylark/blob/development/capi/matrix_types.cpp#L45) function. 

KernelRidge regression is going to accept El::ElementalMatrix<T> as a type.

**Comment by haimav** [comment]
I am not sure the code will be correct for ElementalMatrix. Just use skylark_void2any instead...

**Comment by jomsdev** [comment]
Casting with skylark_void2any worked as you suggested.
