### ISSUE TITLE
Choosing an orientation "standard" Rows 0 Columns 1

### ISSUE THREAD

**Issue by jomsdev** [xdata-skylark/libskylark#46]
Elemental has its own way to specify how a matrix has to be treated. (El::Normal, El::Transpose...)

With Skylark we have the [skylark::base::direction_t](https://github.com/xdata-skylark/libskylark/blob/development/base/basic.hpp#L6) enum. However, in order to expose this enum to the C API we have [two defines](https://github.com/xdata-skylark/libskylark/blob/development/capi/basec.hpp#L15). We are defining columns as 1 and rows as 2. This is the Int that we are going to receive from python and "convert it" to the good  skylark::base::direction_t.  We can not use directly  skylark::base::direction_t  because in the enum Rows are defined as 0 and Columns as 1.

I propose do it congruent and use always 0 for Rows and 1 for columns. Would be easy then reason about the software and be sure that the same function in python/c++ with the same parameters has the same behavior.

**Comment by haimav** [comment]
Yes this makes sense.

**Comment by poulson** [comment]
FWIW, a C++ enum has the ABI of an `unsigned int`, with the first enum value defaulting to 0, and subsequent values incrementing by one. Thus python can easily be made to be compatible via ctypes.
