### ISSUE TITLE
CMake -DBUILD_ML=OFF does not deactivete some CLI tools

### ISSUE THREAD

**Issue by jomsdev** [xdata-skylark/libskylark#50]
Running the command make after 

``` bash
CC=mpicc CXX=mpicxx cmake -DBUILD_ML=OFF -DUSE_FFTW=ON -DUSE_COMBBLAS=ON -DBOOST_ROOT=/usr/local/include -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=${SKYLARK_INSTALL_DIR} ${SKYLARK_SRC_DIR}
```

compiles three targets: capi (libskylark.so), skylark_linear, skylark_svd.

I think this is not how it should work because -DBUILD_ML=OFF. Is this the normal behavior or we have to change it?

**Comment by jomsdev** [comment]
If this is not ML we could have -DBUILD_NLA

**Comment by haimav** [comment]
-DBUILD_ML=OFF only turns off the building of cli under ml. The ones you mention are under nla. We should probably have also a -DBUILD_NLA.

**Comment by jomsdev** [comment]
Effectively, we have an -DBUILD_NLA too.

I have moved both ML and NLA applications to its own folder. I think that it is not really a "feature" and should have their own space. 

Do you have any objection? @haimav @gidiko
