### ISSUE TITLE
FJLT: Matrix -> Matrix

### ISSUE THREAD

**Issue by gidiko** [xdata-skylark/libskylark#62]
We need to have the combination: FJLT on Matrix objects and get Matrix objects back. 

- This specialization should be in sketch/FJLT_Elemental.hpp ... basically a copy/paste of the DistMatrix -> DistMatrix specialization starting in https://github.com/xdata-skylark/libskylark/blob/master/sketch/FJLT_Elemental.hpp#L732 with DistMatrix replaced by Matrix ;)

- Then in capi/csketch.cpp we should add the line: SKDEF(FJLT, Matrix, Matrix)

- Also we add a corresponding line in sketch/FJLT.hpp in "any, any" part combinations

- ... compiler complaints will perhaps tell us that we need some extra tweaks ;)

**Comment by jomsdev** [comment]
Hi Giorgios,

Thank you for the detailed issue. I will take a look on it.

**Comment by jomsdev** [comment]
@gidiko solved in #64 and pending to be accepted.

**Comment by jomsdev** [comment]
Reviewed and accepted.
