### ISSUE TITLE
Error while compiling skylark - ElementalMatrix not found

### ISSUE THREAD

**Issue by armandology** [xdata-skylark/libskylark#7]
I have been trying to compile skylark with following script:

module load python/python-2.7.8-gcc-4.9.2
module load cmake/cmake-3.2.2-gcc-4.9.2
module load openblas/openblas-0.2.13-gcc-4.9.2
module load lapack/lapack-3.5.0-gcc-4.9.2
module load boost/boost-1.57.0-openmpi-1.8.3-gcc-4.9.2
module load openmpi/openmpi-1.8.3-gcc-4.9.2
module load hdf5/hdf5-1.8.14-gcc-4.9.2
module load elemental/elemental-0.86-rc1-openmpi-1.8.3-gcc-4.9.2
module load fftw/fftw-3.3.4-openmpi-1.8.3-gcc-4.9.2
module load random123/random123-1.08

export SL=skylark-2016-03-15
mkdir $SL-build
cd $SL-build

cmake ../$SL -DCMAKE_BUILD_TYPE=HybridRel -DCMAKE_INSTALL_PREFIX="/apps/$SL-openmpi-1.8.3-gcc-4.9.2"

And I get these errors:

[agoel@euser1 skylark-2016-03-15-build]$ make
Scanning dependencies of target cskylark
[ 14%] Building CXX object sketch/capi/CMakeFiles/cskylark.dir/capi.cpp.o
In file included from /srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/computed_matrix.hpp:4:0,
                 from /srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/base.hpp:18,
                 from /srcs/skylark/skylark-2016-03-15/sketch/capi/../sketch.hpp:4,
                 from /srcs/skylark/skylark-2016-03-15/sketch/capi/sketchc.hpp:10,
                 from /srcs/skylark/skylark-2016-03-15/sketch/capi/capi.cpp:3:
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/../utility/typer.hpp:32:17: error: ‘ElementalMatrix’ is not a member of ‘El’
 struct typer_t< El::ElementalMatrix<F> > {
                 ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/../utility/typer.hpp:32:17: error: ‘ElementalMatrix’ is not a member of ‘El’
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/../utility/typer.hpp:32:38: error: template argument 1 is invalid
 struct typer_t< El::ElementalMatrix<F> > {
                                      ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/../utility/typer.hpp:32:40: error: expected unqualified-id before ‘>’ token
 struct typer_t< El::ElementalMatrix<F> > {
                                        ^
In file included from /srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/base.hpp:22:0,
                 from /srcs/skylark/skylark-2016-03-15/sketch/capi/../sketch.hpp:4,
                 from /srcs/skylark/skylark-2016-03-15/sketch/capi/sketchc.hpp:10,
                 from /srcs/skylark/skylark-2016-03-15/sketch/capi/capi.cpp:3:
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:31:28: error: variable or field ‘ColumnView’ declared void
 inline void ColumnView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                            ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:31:24: error: ‘ElementalMatrix’ is not a member of ‘El’
 inline void ColumnView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                        ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:31:45: error: expected primary-expression before ‘>’ token
 inline void ColumnView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                                             ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:31:48: error: ‘A’ was not declared in this scope
 inline void ColumnView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                                                ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:31:51: error: ‘ElementalMatrix’ is not a member of ‘El’
 inline void ColumnView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                                                   ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:31:72: error: expected primary-expression before ‘>’ token
 inline void ColumnView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                                                                        ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:31:75: error: ‘B’ was not declared in this scope
 inline void ColumnView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                                                                           ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:32:13: error: expected primary-expression before ‘j’
     El::Int j, El::Int width) {
             ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:32:24: error: expected primary-expression before ‘width’
     El::Int j, El::Int width) {
                        ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:37:28: error: variable or field ‘ColumnView’ declared void
 inline void ColumnView(El::ElementalMatrix<T>& A, const El::ElementalMatrix<T>& B,
                            ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:37:24: error: ‘ElementalMatrix’ is not a member of ‘El’
 inline void ColumnView(El::ElementalMatrix<T>& A, const El::ElementalMatrix<T>& B,
                        ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:37:45: error: expected primary-expression before ‘>’ token
 inline void ColumnView(El::ElementalMatrix<T>& A, const El::ElementalMatrix<T>& B,
                                             ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:37:48: error: ‘A’ was not declared in this scope
 inline void ColumnView(El::ElementalMatrix<T>& A, const El::ElementalMatrix<T>& B,
                                                ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:37:51: error: expected primary-expression before ‘const’
 inline void ColumnView(El::ElementalMatrix<T>& A, const El::ElementalMatrix<T>& B,
                                                   ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:38:13: error: expected primary-expression before ‘j’
     El::Int j, El::Int width) {
             ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:38:24: error: expected primary-expression before ‘width’
     El::Int j, El::Int width) {
                        ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:57:25: error: variable or field ‘RowView’ declared void
 inline void RowView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                         ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:57:21: error: ‘ElementalMatrix’ is not a member of ‘El’
 inline void RowView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                     ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:57:42: error: expected primary-expression before ‘>’ token
 inline void RowView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                                          ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:57:45: error: ‘A’ was not declared in this scope
 inline void RowView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                                             ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:57:48: error: ‘ElementalMatrix’ is not a member of ‘El’
 inline void RowView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                                                ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:57:69: error: expected primary-expression before ‘>’ token
 inline void RowView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                                                                     ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:57:72: error: ‘B’ was not declared in this scope
 inline void RowView(El::ElementalMatrix<T>& A, El::ElementalMatrix<T>& B,
                                                                        ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:58:13: error: expected primary-expression before ‘i’
     El::Int i, El::Int height) {
             ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:58:24: error: expected primary-expression before ‘height’
     El::Int i, El::Int height) {
                        ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:63:25: error: variable or field ‘RowView’ declared void
 inline void RowView(El::ElementalMatrix<T>& A,
                         ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:63:21: error: ‘ElementalMatrix’ is not a member of ‘El’
 inline void RowView(El::ElementalMatrix<T>& A,
                     ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:63:42: error: expected primary-expression before ‘>’ token
 inline void RowView(El::ElementalMatrix<T>& A,
                                          ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:63:45: error: ‘A’ was not declared in this scope
 inline void RowView(El::ElementalMatrix<T>& A,
                                             ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:64:5: error: expected primary-expression before ‘const’
     const El::ElementalMatrix<T>& B,
     ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:65:13: error: expected primary-expression before ‘i’
     El::Int i, El::Int height) {
             ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/viewing.hpp:65:24: error: expected primary-expression before ‘height’
     El::Int i, El::Int height) {
                        ^
In file included from /srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/base.hpp:29:0,
                 from /srcs/skylark/skylark-2016-03-15/sketch/capi/../sketch.hpp:4,
                 from /srcs/skylark/skylark-2016-03-15/sketch/capi/sketchc.hpp:10,
                 from /srcs/skylark/skylark-2016-03-15/sketch/capi/capi.cpp:3:
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:40:15: error: ‘ElementalMatrix’ in namespace ‘El’ does not name a template type
     const El::ElementalMatrix<T> &A, const El::ElementalMatrix<T> &B,
               ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:40:30: error: expected ‘,’ or ‘...’ before ‘<’ token
     const El::ElementalMatrix<T> &A, const El::ElementalMatrix<T> &B,
                              ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp: In function ‘void skylark::base::EuclideanDistanceMatrix(skylark::base::direction_t, skylark::base::direction_t, T, int)’:
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:43:12: error: ‘C’ was not declared in this scope
     T *c = C.Buffer();
            ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:47:60: error: ‘A’ was not declared in this scope
         El::Gemm(El::ADJOINT, El::NORMAL, T(-2.0) * alpha, A, B, T(beta), C);
                                                            ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:47:63: error: ‘B’ was not declared in this scope
         El::Gemm(El::ADJOINT, El::NORMAL, T(-2.0) * alpha, A, B, T(beta), C);
                                                               ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:47:68: error: ‘beta’ was not declared in this scope
         El::Gemm(El::ADJOINT, El::NORMAL, T(-2.0) * alpha, A, B, T(beta), C);
                                                                    ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp: At global scope:
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:101:24: error: ‘ElementalMatrix’ in namespace ‘El’ does not name a template type
     T alpha, const El::ElementalMatrix<T> &A,
                        ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:101:39: error: expected ‘,’ or ‘...’ before ‘<’ token
     T alpha, const El::ElementalMatrix<T> &A,
                                       ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp: In function ‘void skylark::base::SymmetricEuclideanDistanceMatrix(El::UpperOrLowerNS::UpperOrLower, skylark::base::direction_t, T, int)’:
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:104:12: error: ‘C’ was not declared in this scope
     T *c = C.Buffer();
            ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:108:51: error: ‘A’ was not declared in this scope
         El::Herk(uplo, El::ADJOINT, -2.0 * alpha, A, beta, C);
                                                   ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:108:54: error: ‘beta’ was not declared in this scope
         El::Herk(uplo, El::ADJOINT, -2.0 * alpha, A, beta, C);
                                                      ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp: At global scope:
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:170:15: error: ‘ElementalMatrix’ in namespace ‘El’ does not name a template type
     const El::ElementalMatrix<T> &APre, const El::ElementalMatrix<T> &BPre,
               ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:170:30: error: expected ‘,’ or ‘...’ before ‘<’ token
     const El::ElementalMatrix<T> &APre, const El::ElementalMatrix<T> &BPre,
                              ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp: In function ‘void skylark::base::L1DistanceMatrix(skylark::base::direction_t, skylark::base::direction_t, T, int)’:
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:177:27: error: ‘CPre’ was not declared in this scope
         const El::Int m = CPre.Height();
                           ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:179:32: error: ‘BPre’ was not declared in this scope
         const El::Int sumDim = BPre.Height();
                                ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:181:29: error: ‘APre’ was not declared in this scope
         const El::Grid& g = APre.Grid();
                             ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:183:9: error: ‘DistMatrixReadProxy’ is not a member of ‘El’
         El::DistMatrixReadProxy<T, T, El::MC, El::MR> AProx(APre);
         ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:183:34: error: expected primary-expression before ‘,’ token
         El::DistMatrixReadProxy<T, T, El::MC, El::MR> AProx(APre);
                                  ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:183:37: error: expected primary-expression before ‘,’ token
         El::DistMatrixReadProxy<T, T, El::MC, El::MR> AProx(APre);
                                     ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:183:65: error: there are no arguments to ‘AProx’ that depend on a template parameter, so a declaration of ‘AProx’ must be available [-fpermissive]
         El::DistMatrixReadProxy<T, T, El::MC, El::MR> AProx(APre);
                                                                 ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:183:65: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:184:9: error: ‘DistMatrixReadProxy’ is not a member of ‘El’
         El::DistMatrixReadProxy<T, T, El::MC, El::MR> BProx(BPre);
         ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:184:34: error: expected primary-expression before ‘,’ token
         El::DistMatrixReadProxy<T, T, El::MC, El::MR> BProx(BPre);
                                  ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:184:37: error: expected primary-expression before ‘,’ token
         El::DistMatrixReadProxy<T, T, El::MC, El::MR> BProx(BPre);
                                     ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:184:65: error: there are no arguments to ‘BProx’ that depend on a template parameter, so a declaration of ‘BProx’ must be available [-fpermissive]
         El::DistMatrixReadProxy<T, T, El::MC, El::MR> BProx(BPre);
                                                                 ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:185:9: error: ‘DistMatrixReadWriteProxy’ is not a member of ‘El’
         El::DistMatrixReadWriteProxy<T, T, El::MC, El::MR> CProx(CPre);
         ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:185:39: error: expected primary-expression before ‘,’ token
         El::DistMatrixReadWriteProxy<T, T, El::MC, El::MR> CProx(CPre);
                                       ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:185:42: error: expected primary-expression before ‘,’ token
         El::DistMatrixReadWriteProxy<T, T, El::MC, El::MR> CProx(CPre);
                                          ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:185:70: error: there are no arguments to ‘CProx’ that depend on a template parameter, so a declaration of ‘CProx’ must be available [-fpermissive]
         El::DistMatrixReadWriteProxy<T, T, El::MC, El::MR> CProx(CPre);
                                                                      ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:186:19: error: ‘AProx’ was not declared in this scope
         auto& A = AProx.GetLocked();
                   ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:187:19: error: ‘BProx’ was not declared in this scope
         auto& B = BProx.GetLocked();
                   ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:188:19: error: ‘CProx’ was not declared in this scope
         auto& C = CProx.Get();
                   ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:197:19: error: ‘beta’ was not declared in this scope
         El::Scale(beta, C);
                   ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp: At global scope:
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:298:15: error: ‘ElementalMatrix’ in namespace ‘El’ does not name a template type
     const El::ElementalMatrix<T> &APre, T beta, El::ElementalMatrix<T> &CPre) {
               ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:298:30: error: expected ‘,’ or ‘...’ before ‘<’ token
     const El::ElementalMatrix<T> &APre, T beta, El::ElementalMatrix<T> &CPre) {
                              ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp: In function ‘void skylark::base::SymmetricL1DistanceMatrix(El::UpperOrLowerNS::UpperOrLower, skylark::base::direction_t, T, int)’:
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:302:27: error: ‘APre’ was not declared in this scope
         const El::Int r = APre.Height();
                           ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:306:9: error: ‘DistMatrixReadProxy’ is not a member of ‘El’
         El::DistMatrixReadProxy<T, T, El::MC, El::MR> AProx(APre);
         ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:306:34: error: expected primary-expression before ‘,’ token
         El::DistMatrixReadProxy<T, T, El::MC, El::MR> AProx(APre);
                                  ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:306:37: error: expected primary-expression before ‘,’ token
         El::DistMatrixReadProxy<T, T, El::MC, El::MR> AProx(APre);
                                     ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:306:65: error: there are no arguments to ‘AProx’ that depend on a template parameter, so a declaration of ‘AProx’ must be available [-fpermissive]
         El::DistMatrixReadProxy<T, T, El::MC, El::MR> AProx(APre);
                                                                 ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:307:9: error: ‘DistMatrixReadWriteProxy’ is not a member of ‘El’
         El::DistMatrixReadWriteProxy<T, T, El::MC, El::MR> CProx(CPre);
         ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:307:39: error: expected primary-expression before ‘,’ token
         El::DistMatrixReadWriteProxy<T, T, El::MC, El::MR> CProx(CPre);
                                       ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:307:42: error: expected primary-expression before ‘,’ token
         El::DistMatrixReadWriteProxy<T, T, El::MC, El::MR> CProx(CPre);
                                          ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:307:66: error: ‘CPre’ was not declared in this scope
         El::DistMatrixReadWriteProxy<T, T, El::MC, El::MR> CProx(CPre);
                                                                  ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:307:70: error: there are no arguments to ‘CProx’ that depend on a template parameter, so a declaration of ‘CProx’ must be available [-fpermissive]
         El::DistMatrixReadWriteProxy<T, T, El::MC, El::MR> CProx(CPre);
                                                                      ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:308:19: error: ‘AProx’ was not declared in this scope
         auto& A = AProx.GetLocked();
                   ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:309:19: error: ‘CProx’ was not declared in this scope
         auto& C = CProx.Get();
                   ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:318:28: error: ‘beta’ was not declared in this scope
         El::ScaleTrapezoid(beta, uplo, C);
                            ^
/srcs/skylark/skylark-2016-03-15/sketch/capi/../../base/distance.hpp:321:44: error: ‘ALL’ is not a member of ‘El’
             auto A1 = A(El::IR(k, k + nb), El::ALL);
                                            ^

**Comment by iff** [comment]
Are you using the `0.86-rc1` tag for your Elemental module (or what git hash was used to build Elemental)? Due to the changes in the Elemental API we currently support/require the Elemental `0ffa9fc29ab740a7a96eccc45c180463723f465d` [commit](https://github.com/elemental/Elemental/commit/0ffa9fc29ab740a7a96eccc45c180463723f465d). If your module is older/newer this will most probably lead to compile issues. I will update the docs to reflect this later this week.
What branch/commit are you actually trying to build?

**Comment by poulson** [comment]
I would highly recommend everyone standardizing on the current dev branch; I'm long overdue for a release but will be dedicating a significant amount of time towards this goal in the next two months.

**Comment by armandology** [comment]
The Elemental was downloaded and installed as per instructions on skylark page: http://xdata-skylark.github.io/libskylark/docs/stable/sphinx/installation.html

This page asks to download from: Currently version 0.86 is not officially released yet. Please, use the release candidate, e.g. https://github.com/elemental/Elemental/releases/tag/0.86-rc1

**Comment by armandology** [comment]
So should I download and compile from dev branch ?

**Comment by poulson** [comment]
Sorry, I don't mean to contradict the official skylark instructions.

**Comment by iff** [comment]
Please follow this [steps](https://github.com/xdata-skylark/libskylark/blob/development/vagrant/trusty64/bootstrap.sh#L175) for now.

**Comment by iff** [comment]
@armandology: did you ever manage to resolve the issues?

**Comment by armandology** [comment]
Yes I was able to build using the instructions you provided earlier: "Please follow this steps <https://github.com/xdata-skylark/libskylark/blob/development/vagrant/trusty64/bootstrap.sh#L175> for now.”

Many thanks.

However, I am just the sysadmin, and the actual professor who has to use the system for research hasn’t gotten back to me if there are any issues, so it seems all is good :-)

Regards

Amit

**Comment by iff** [comment]
Ok, closing this issue.
