### ISSUE TITLE
Comparison between libskylark and fasttext.

### ISSUE THREAD

**Issue by shyamalschandra** [xdata-skylark/libskylark#72]
Do you plan on comparing libskylark and fasttext in terms of computing word embeddings?

Github for fasttext:
https://github.com/facebookresearch/fastText

**Comment by shyamalschandra** [comment]
Did you get this message?

**Comment by haimav** [comment]
That would be something interesting to do, but currently no  plans to actually do it and the foreseeable future... (just too busy)

**Comment by shyamalschandra** [comment]
Thank you for responding!
