### ISSUE TITLE
KDT install error

### ISSUE THREAD

**Issue by yinjiehuang** [xdata-skylark/libskylark#8]
Hi, I am following this [https://github.com/xdata-skylark/libskylark/blob/development/vagrant/trusty64/bootstrap.sh] to deploy Skylark in EC2 AWS.

Everything works fine until the step of "KDT", when I input "python ./setup.py build 1> /dev/null", I got the following error:

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from kdt/pyCombBLAS/../../CombBLAS/psort-1.0/src/psort.h:26:0,
                 from kdt/pyCombBLAS/../../CombBLAS/SpDefs.h:50,
                 from kdt/pyCombBLAS/../../CombBLAS/CombBLAS.h:71,
                 from kdt/pyCombBLAS/pyCombBLAS.h:10,
                 from kdt/pyCombBLAS/pyCombBLAS.cpp:3:
kdt/pyCombBLAS/../../CombBLAS/psort-1.0/src/psort_util.h:26:17: fatal error: mpi.h: No such file or directory
 #include <mpi.h>
                 ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Any idea why this is happening? Thanks a lot for the help.

**Comment by iff** [comment]
Hi, could you attach the full log file?
In the meantime, did you look at Haims [starcluster approach](https://github.com/haimav/starcluster-libskylark) to build an image for AWS?

**Comment by haimav** [comment]
Hi Yinjie,

CombBLAS & KDT are not an hard requirement. For 99% of what you would want to do with libskylark, they are not needed. I suggest you just skip their installation.

If you want to get up and running quickly on EC2, I suggest you just use the [script](https://github.com/haimav/starcluster-libskylark)

**Comment by yinjiehuang** [comment]
@haimav @iff  Thanks for the reply.
I was following the starcluster approach to build an image these days. However, I still have some problems:
1) Some how my starcluseter does not support c4.large instance, so I use c3.large instead. Besides, I use Ubuntu 14.04.
2) I followed the script till the last step. Then I exited the instance and created the image. The image can be created. But the instance "check status" becomes "1/2 checks passed" and I can not ssh back into this instance anymore. Any idea why this is happening?

Even if I created the new instance with this new image, "1/2 checks passed" problem is still there. Could you please help me with this?

**Comment by haimav** [comment]
@yinjiehuang For c4.large: The bleeding-edge latest version of StarCluster from github has support for that. It is not supported in the latest official release. Do you want to try that out instead of trying to figure out what is the problem with c3.large and the latest official starcluster?

**Comment by yinjiehuang** [comment]
@haimav I tried c4.large, the problem is still there. The instance is fine and healthy after I install all the softwares following the script. Then I exit the instance and "starcluster ebsimage i-XXXXXXXX hvmimage", after some time, the instance's status changes from "2/2 check" to "1/2 check". I can not log in to the instance after the image is created. Any idea? I am using Ubuntu 14.04 and in North Virginia Region. Could you please help me with this?

**Comment by haimav** [comment]
@yinjiehuang Is there a reason you are using 14.04? When I created the script I used 15.04 in the Oregon region. I can try 14.04 in North Virginia tomorrow... I somehow vaguely remember there were some problems with 14.04 and this is why I used 15.04 (not sure... it was a few months ago).

**Comment by yinjiehuang** [comment]
@haimav It is working now if I use 15.04 Ubuntu. Thanks a lot for the help.

**Comment by yinjiehuang** [comment]
@haimav 
After installing libskylark, I tried to run this command "skylark_svd -help", however, I got this:
"skylark_svd: error while loading shared libraries: libEl.so: cannot open shared object file: No such file or directory"
Why is this happening? Thanks a lot for the help.

**Comment by haimav** [comment]
That is very weird...

Did you create the AMI after installing Elemental?
Is there a libEl.so under /usr/local/lib?
Can you ldd skylark_svd?

**Comment by yinjiehuang** [comment]
@haimav 
I crated AMI after installing Elemental. I have libEl.so under /usr/local/lib.
I got this after "ldd skylark_svd":
        linux-vdso.so.1 =>  (0x00007ffda5566000)
	libEl.so => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa8d8963000)
	libboost_filesystem.so.1.60.0 => not found
	libfftw3f.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3f.so.3 (0x00007fa8d8557000)
	libfftw3.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3.so.3 (0x00007fa8d8159000)
	libmpich.so.12 => /usr/lib/x86_64-linux-gnu/libmpich.so.12 (0x00007fa8d7cd5000)
	libboost_mpi.so.1.60.0 => not found
	libboost_program_options.so.1.60.0 => not found
	libboost_serialization.so.1.60.0 => not found
	libboost_system.so.1.60.0 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa8d79c5000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fa8d77ad000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa8d7597000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa8d71cd000)
	libmpl.so.1 => /usr/lib/x86_64-linux-gnu/libmpl.so.1 (0x00007fa8d6fc6000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa8d6dbe000)
	libcr.so.0 => /usr/lib/libcr.so.0 (0x00007fa8d6bb4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa8d6995000)
	/lib64/ld-linux-x86-64.so.2 (0x000055724a88c000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa8d6791000)

There are several items not found. Why?

**Comment by haimav** [comment]
It looks like /usr/local/lib is not in the library load path. Weird...  Perhaps try doing
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

**Comment by yinjiehuang** [comment]
@haimav 
Problem solved, Thanks a lot.
