### ISSUE TITLE
problem running "mpiexec -np 2 skylark_ml"

### ISSUE THREAD

**Issue by yinjiehuang** [xdata-skylark/libskylark#9]
Hi, 

After I created AMI and started a 2 node cluster, I used skylark_ml to run some examples and got some problem.

I downloaded "usps.bz2" and "usps.t.bz2" from LIBSVM datasets. Then train the svm model using "mpiexec -np 2 skylark_ml -g 10 -k 1 -l 2 -i 30 -f 1000 --trainfile data/usps --modelfile model"
This is the output I got:
" Generated using skylark_mlusing the following command-line:
	skylark_ml -g 10 -k 1 -l 2 -i 30 -f 1000 --trainfile data/usps --modelfile model

 Regression? = False
 Training File = data/usps
 Model File = model
 Validation File =
 Test File =
 File Format = 0
 Loss function = 2 (Hinge Loss (SVMs))
 Regularizer = 0 (No Regularizer)
 Kernel = 1 (Gaussian)
 Kernel Parameter = 10
 Second Kernel Parameter = 0
 Third Kernel Parameter = 1
 Regularization Parameter = 0
 Maximum Iterations = 30
 Tolerance = 0.001
 rho = 1
 Seed = 12345
 Random Features = 1000
 Cache transforms? = False
 Use fast, if availble? = False
 Sequence = 0 (Monte Carlo)
 Number of feature partitions = 1
 Threads = 1
 Number of MPI Processes = 2
Mode: Training. Loading data...
Reading from file data/usps
Reading and distributing chunk 0 to 7290 (7291 elements )
Read Matrix with dimensions: 7291 by 256 (1.28793secs)
iteration 1 objective 80201 time 3.02117 seconds
iteration 2 objective 80201 time 3.49942 seconds
iteration 3 objective 29499.2 time 3.97123 seconds
iteration 4 objective 2232.66 time 4.44345 seconds
iteration 5 objective 1591.5 time 4.91736 seconds
iteration 6 objective 1484.09 time 5.39406 seconds
iteration 7 objective 1538.1 time 5.86425 seconds
iteration 8 objective 1628.2 time 6.33547 seconds
iteration 9 objective 1452.38 time 6.80624 seconds
iteration 10 objective 1248.62 time 7.28087 seconds
iteration 11 objective 1125.84 time 7.73885 seconds
iteration 12 objective 1055.95 time 8.21675 seconds
iteration 13 objective 1008.02 time 8.69418 seconds
iteration 14 objective 963.049 time 9.16695 seconds
iteration 15 objective 916.237 time 9.64013 seconds
iteration 16 objective 870.424 time 10.1192 seconds
iteration 17 objective 828.925 time 10.5949 seconds
iteration 18 objective 791.522 time 11.0673 seconds
iteration 19 objective 758.095 time 11.5416 seconds
iteration 20 objective 727.587 time 12.0193 seconds
iteration 21 objective 699.01 time 12.4916 seconds
iteration 22 objective 672.107 time 12.9662 seconds
iteration 23 objective 646.775 time 13.4412 seconds
iteration 24 objective 623.086 time 13.9164 seconds
iteration 25 objective 601.242 time 14.3945 seconds
iteration 26 objective 580.814 time 14.8692 seconds
iteration 27 objective 561.493 time 15.3433 seconds
iteration 28 objective 543.803 time 15.8222 seconds
iteration 29 objective 527.182 time 16.2979 seconds
iteration 30 objective 511.685 time 16.7682 seconds"

Then I used this
"mpiexec -np 2 skylark_ml --outputfile output --testfile data/usps.t --modelfile model" and got error:
"Mode: Predicting (from file). Loading data...
 Generated using skylark_mlusing the following command-line:
	skylark_ml --outputfile output --testfile data/usps.t --modelfile model

 Regression? = False
 Training File =
 Model File = model
 Validation File =
 Test File = data/usps.t
 File Format = 0
 Loss function = 0 (Squared Loss)
 Regularizer = 0 (No Regularizer)
 Kernel = 0 (Linear)
 Kernel Parameter = 1
 Second Kernel Parameter = 0
 Third Kernel Parameter = 1
 Regularization Parameter = 0
 Maximum Iterations = 20
 Tolerance = 0.001
 rho = 1
 Seed = 12345
 Random Features = 0
 Cache transforms? = False
 Use fast, if availble? = False
 Sequence = 0 (Monte Carlo)
 Number of feature partitions = 1
 Threads = 1
 Number of MPI Processes = 2
Reading from file data/usps.t
Reading and distributing chunk 0 to 2006 (2007 elements )
Read Matrix with dimensions: 2007 by 256 (0.357021secs)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 31382 RUNNING AT master
=   EXIT CODE: 134
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES

YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions"

If I use the "skylark_ml --outputfile output --testfile data/usps.t --modelfile model", the output can be generated correctly
"Mode: Predicting (from file). Loading data...
 Generated using skylark_mlusing the following command-line:
	skylark_ml --outputfile output --testfile data/usps.t --modelfile model

 Regression? = False
 Training File =
 Model File = model
 Validation File =
 Test File = data/usps.t
 File Format = 0
 Loss function = 0 (Squared Loss)
 Regularizer = 0 (No Regularizer)
 Kernel = 0 (Linear)
 Kernel Parameter = 1
 Second Kernel Parameter = 0
 Third Kernel Parameter = 1
 Regularization Parameter = 0
 Maximum Iterations = 20
 Tolerance = 0.001
 rho = 1
 Seed = 12345
 Random Features = 0
 Cache transforms? = False
 Use fast, if availble? = False
 Sequence = 0 (Monte Carlo)
 Number of feature partitions = 1
 Threads = 1
 Number of MPI Processes = 1
Reading from file data/usps.t
Reading and distributing chunk 0 to 2006 (2007 elements )
Read Matrix with dimensions: 2007 by 256 (0.190427secs)
Test Accuracy = 94.6687 %"

Why is this happening? Any idea?

**Comment by iff** [comment]
What instance types did you use for the nodes?

**Comment by haimav** [comment]
I found the bug and will issue a fix very soon.

**Comment by yinjiehuang** [comment]
@iff I am using c4.large. @haimav  Thanks a lot.

**Comment by haimav** [comment]
@yinjiehuang The development branch now has the fix.

Note that to get mpiexec to use other nodes in the cluster you need to use the -f flag for mpiexec and provide it with a host file (with your command both processes are on the master node).

**Comment by yinjiehuang** [comment]
**@haimav Thanks for the help.
I reinstalled skylark with the bug fix, I tried "mpiexec -np 2 skylark_ml --outputfile output --testfile data/usps.t --modelfile model" again, however, I have the following error message:**

Mode: Predicting (from file). Loading data...
Generated using skylark_mlusing the following command-line: 
	skylark_ml --outputfile output --testfile data/usps.t --modelfile model

 Regression? = False
 Training File = 
 Model File = model
 Validation File = 
 Test File = data/usps.t
 File Format = 0
 Loss function = 0 (Squared Loss)
 Regularizer = 0 (No Regularizer)
 Kernel = 0 (Linear)
 Kernel Parameter = 1
 Second Kernel Parameter = 0
 Third Kernel Parameter = 1
 Regularization Parameter = 0
 Maximum Iterations = 20
 Tolerance = 0.001
 rho = 1
 Seed = 12345
 Random Features = 0
 Cache transforms? = False
 Use fast, if availble? = False
 Sequence = 0 (Monte Carlo)
 Number of feature partitions = 1
 Threads = 1
 Number of MPI Processes = 2
Reading from file data/usps.t
Reading and distributing chunk 0 to 2006 (2007 elements )
Read Matrix with dimensions: 2007 by 256 (0.362298secs)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc


=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 12933 RUNNING AT master
=   EXIT CODE: 134
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES

YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

**Besides, I created the host file "hosts" with the two nodes names contained ("master" and "node001"). Then I ran this: 
"mpiexec -f hosts -np 2 skylark_ml -g 10 -k 1 -l 2 -i 30 -f 1000 --trainfile data/usps --modelfile model"
However, I got the error:**
[proxy:0:1@node001] HYDU_create_process (utils/launch/launch.c:75): execvp error on file skylark_ml (No such file or directory)


=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 1678 RUNNING AT node001
=   EXIT CODE: 255
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES

[proxy:0:0@master] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:886): assert (!closed) failed
[proxy:0:0@master] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@master] main (pm/pmiserv/pmip.c:206): demux engine error waiting for event
[mpiexec@master] HYDT_bscu_wait_for_completion (tools/bootstrap/utils/bscu_wait.c:76): one of the processes terminated badly; aborting
[mpiexec@master] HYDT_bsci_wait_for_completion (tools/bootstrap/src/bsci_wait.c:23): launcher returned error waiting for completion
[mpiexec@master] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:218): launcher returned error waiting for completion
[mpiexec@master] main (ui/mpich/mpiexec.c:336): process manager error waiting for completion
"
**Could you please help me with this?**

**Comment by haimav** [comment]
@yinjiehuang For the hosts file, you should use ./skylark_ml instead of skylark_ml

Did you do "git pull" and then "get checkout development" before recompiling skylark?
The bug fix is now also in the master branch, so just doing "git pull" and compiling skylark_ml should fix things.

**Comment by yinjiehuang** [comment]
@haimav 
I opened a brand new, two-node cluster and git clone the newest repository. I was trying to compile the newest version of libskylark, however, after "make" command, when I "make install", I got the following error:

...
-- Up-to-date: /usr/local/include/skylark/sketch/hash_transform_Elemental.hpp
-- Up-to-date: /usr/local/lib/libcskylark.so
-- Up-to-date: /usr/local/include/skylark/basec.hpp
CMake Error at capi/cmake_install.cmake:54 (file):
  file INSTALL cannot find "/root/libskylark/capi/FILES".
Call Stack (most recent call first):
  cmake_install.cmake:721 (include)


Makefile:66: recipe for target 'install' failed
make: *** [install] Error 1

Why is this happening? I could install it before.

**Comment by iff** [comment]
Yep, the current CMake file in CAPI is broken. I'll fix it as soon as we decided where to install the files. For now you can just comment lines [40 - 45](https://github.com/xdata-skylark/libskylark/blob/master/capi/CMakeLists.txt#L40-L45) in the `capi/CMakeLists.txt` file.

**Comment by iff** [comment]
Pushed a commit that should fix this issue.

**Comment by yinjiehuang** [comment]
@iff @haimav Thanks, it is working now.
